# Generated by Django 5.2.4 on 2025-07-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_img', models.ImageField(upload_to='uploads/')),
                ('name_img', models.CharField(max_length=100)),
            ],
        ),
    ]
