# Generated by Django 5.2.4 on 2025-07-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_img', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=100)),
                ('disc', models.CharField(max_length=200)),
            ],
        ),
    ]
