# Generated by Django 5.2.4 on 2025-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_legacymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(default='Untitled', max_length=100)),
                ('name_set', models.TextField()),
                ('description1', models.TextField(default='Untitled')),
                ('description2', models.TextField(default='Untitled')),
                ('description3', models.TextField(default='Untitled')),
                ('g_img', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='legacymodel',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='legacymodel',
            name='title',
        ),
        migrations.AddField(
            model_name='legacymodel',
            name='disc1',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AddField(
            model_name='legacymodel',
            name='disc2',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AddField(
            model_name='legacymodel',
            name='disc3',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AddField(
            model_name='legacymodel',
            name='title1',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
