# Generated by Django 5.2.4 on 2025-07-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_groupmodel_remove_legacymodel_disc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='title2',
            new_name='p_title',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='s_title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
