# Generated by Django 5.2.4 on 2025-07-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_title2_groupmodel_p_title_groupmodel_s_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='name_set',
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapp.groupmodel')),
            ],
        ),
    ]
