# Generated by Django 5.2.4 on 2025-07-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_groupmodel_name_set_membermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_img', models.ImageField(upload_to='uploads/')),
                ('f_name', models.CharField(default='Untitled', max_length=100)),
                ('f_title', models.CharField(default='Untitled', max_length=100)),
            ],
        ),
    ]
