# Generated by Django 5.2.4 on 2025-07-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_facultymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_img', models.ImageField(upload_to='uploads/')),
                ('s_name', models.CharField(default='Untitled', max_length=100)),
                ('s_title', models.CharField(default='Untitled', max_length=100)),
            ],
        ),
    ]
