# Generated by Django 5.2.4 on 2025-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_studentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter phone number with country code, e.g. +91XXXXXXXXXX', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SponsorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_img', models.ImageField(upload_to='uploads/')),
                ('other_img', models.ImageField(upload_to='uploads/')),
                ('prev_img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
