# Generated by Django 5.2.4 on 2025-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contactmodel_sponsorsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('year_2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('year_3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('year_4', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('year_5', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('year_6', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
