# Generated by Django 5.2.4 on 2025-07-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_gallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('row2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('row3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryModel',
        ),
    ]
