# Generated by Django 5.2.4 on 2025-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_gallery_1model_delete_gallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstYearPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('row1', models.ImageField(upload_to='uploads/')),
                ('row2', models.ImageField(upload_to='uploads/')),
                ('row3', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FourthYearPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('row1', models.ImageField(upload_to='uploads/')),
                ('row2', models.ImageField(upload_to='uploads/')),
                ('row3', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondYearPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('row1', models.ImageField(upload_to='uploads/')),
                ('row2', models.ImageField(upload_to='uploads/')),
                ('row3', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdYearPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('row1', models.ImageField(upload_to='uploads/')),
                ('row2', models.ImageField(upload_to='uploads/')),
                ('row3', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery_1Model',
        ),
    ]
