# Generated by Django 5.2.4 on 2025-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_firstyearphoto_fourthyearphoto_secondyearphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllYearsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('row1', models.ImageField(upload_to='uploads/')),
                ('row2', models.ImageField(upload_to='uploads/')),
                ('row3', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
